### PR TITLE
docs(links): update to GitHub and main branch

### LINKED ISSUE #8: Broken 'Homepage' link in Nextcloud app store
Hi Julien,

this is just a short note to let you know that the link to your homepage is broken on the **Phonetrack** page in the **Nextcloud app store**.

Page with broken link: https://apps.nextcloud.com/apps/phonetrack

image

Link: [Homepage](https://github.com/julien-nc/phonetrack-oc)

Error message:

image

Regards,

Thomas.

### PR DESCRIPTION
**Pull request by SimJoSt**
Updates the links in the project to the new location on GitHub.

- [x] Other links for the app store and in the app details in the Nextcloud interface, need to be updated as well.
- [x] And many more in the code: https://github.com/search?q=repo%3Ajulien-nc%2Fphonetrack+https%3A%2F%2Fgitlab.com%2Feneiluj%2Fphonetrack-oc&type=code
- [ ] Update wiki links if it would be migrated
- [x] Update badge links if they would be migrated

Resolves #8 and #13

### CODE REVIEW

**Comment by SimJoSt** [comment]
@julien-nc does this help you out? Would you like to add more changes?

**Comment by thiswillbeyourgithub** [comment]
Hi! I don't know if this is taken into account there too but I noticed that the link is wrong also at this page:
https://apps.nextcloud.com/apps/phonetrack

**Comment by SimJoSt** [comment]
@thiswillbeyourgithub yeah, I noticed as well. I think the changes that I made would fix that. I haven't published an app yet, so I am not completely sure about the process or which changes affect what.

**Comment by bonswouar** [comment]
I struggled to find where the actual repository was, please merge this PR ! :smile:
Also it would be less misleading to close the gitlab repository (or at least close issues/PR sections & share the new url)

**Comment by SimJoSt** [comment]
@julien-nc I updated the PR to be ready for review. As the wiki doesn't seem to move over to GitHub, I didn't adjust those links.
Are there any plans for that in the future?

**Comment by julien-nc** [comment]
@SimJoSt Thanks a lot for the PR. I made conflicting changes and then saw this PR. Most of your changes are now in. I just dropped the ones in the translation files. Only the source one is needed.

**Pull request closed without merging**
